# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/plendo
        name: postgres
        username: postgres
        password: root
    jpa:
        database-platform: com.maintacloud.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.use_minimal_puts: true
            javax.persistence.validation.mode: none
    http:
        multipart:
          max-file-size: 5Mb
          max-request-size: 5Mb
liquibase:
    contexts: dev
server:
    port: 8080

# ===================================================================
# MaintaCloud specific properties
# ===================================================================
maintacloud:
    serverInfo:
        serverName: 127.0.0.1
        port: 8080
    plendo:
        uploadedFilePath: D:/tmp
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    cache:
        hazelcast:
            timeToLiveSeconds: 3600
            backupCount: 1
    logging:
        logstash:
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
